#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0-beta-{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  CODECOV_TOKEN: 
    secure: p0ajkgqnPFc6xmwGcsMGJFXgz++MceXp1MuzGn42fAqjvIIUKPN3alcnHDdlbwSJ

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  - sh build.sh

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
before_test:
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory .\OpenCover

# to run your custom scripts instead of automatic tests
test_script:
  - sh test.sh appveyor

# scripts to run after tests
after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f ".\coverage.xml" -X gcov --token=%CODECOV_TOKEN%