#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0-beta-{build}

# branches to build
branches:
  # whitelist
  only:
    - master

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  - sh build.sh

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - sh test.sh